import json

dict_str = '''{
    "Giriş Yap": "Login",
    "Çıkış Yap": "Logout",
    "Kayıtlı CV Yükle": "Load Saved CV",
    "Premium'a Geç": "Go Premium",
    "Premium": "Premium",
    "Ana Sayfa": "Home",
    "Şablonlar": "Templates",
    "Kaydet": "Save",
    "İndir": "Download",
    "İptal": "Cancel",
    "Sil": "Delete",
    "Düzenle": "Edit",
    
    "Profesyonel CV'nizi": "Your Professional CV",
    "Saniyeler İçinde Oluşturun": "Create in Seconds",
    "İçeriğinize odaklanın, tasarımı bize bırakın. Gerçek zamanlı önizleme ile\\r\\n                    mükemmel CV'nizi oluşturun ve PDF olarak indirin.": "Focus on your content, leave the design to us. Create your perfect CV with real-time preview and download as PDF.",
    "İçeriğinize odaklanın, tasarımı bize bırakın. Gerçek zamanlı önizleme ile harika özgeçmişler hazırlayın.": "Focus on your content, leave the design to us. Create amazing resumes with real-time preview.",
    "Şimdi Başla": "Start Now",
    "Neden CV Oluşturucu?": "Why CV Builder?",
    "Harika özellikleri keşfedin": "Discover amazing features",
    "Gerçek Zamanlı Önizleme": "Real-Time Preview",
    "Yazarken CV'nizi anında görerek tam kontrol sahibi olun. Her değişiklik anlık olarak\\r\\n                            yansıtılır.": "Take full control by seeing your CV instantly as you type. Every change is reflected in real-time.",
    "Yazdıkça sonucunu anında görün. Sürpriz yok.": "See the results instantly as you type. No surprises.",
    "Çoklu Şablon Desteği": "Multiple Template Support",
    "Çeşitli profesyonel şablonlar arasından seçim yapın. Tüm endüstriler için uygun tasarımlar.": "Choose from a variety of professional templates. Designs suitable for all industries.",
    "Her mesleğe uygun profesyonel tasarımlar.": "Professional designs for every profession.",
    "A4 Çıktı Uyumluluğu": "A4 Print Compatibility",
    "CV'nizi PDF olarak indirin. A4 boyutunda mükemmel şekilde yazdırılmaya hazır.": "Download your CV as a PDF. Perfectly ready to be printed in A4 size.",
    "PDF olarak kaydederken sıfır kayıp.": "Zero loss when saving as PDF.",
    "Bulut Senkronizasyonu": "Cloud Synchronization",
    "Verileriniz hesabınızda güvenle saklanır. Tüm cihazlarınızdan CV'lerinize dilediğiniz an\\r\\n                            ulaşabilirsiniz.": "Your data is safely stored in your account. You can access your CVs from all your devices anytime.",
    "CV'nizi kaydedin, dilediğiniz yerden düzenleyin.": "Save your CV, edit from anywhere.",
    "CV Şablonları": "CV Templates",
    "Şablonları yatay kaydırarak inceleyin": "Scroll horizontally to view templates",
    "Şablonları Keşfet": "Explore Templates",
    "KLASIK": "CLASSIC",
    "Klasik": "Classic",
    "MODERN": "MODERN",
    "Modern": "Modern",
    "MINIMAL": "MINIMAL",
    "Minimal": "Minimal",
    "CREATIVE": "CREATIVE",
    "Creative": "Creative",
    "TECH": "TECH",
    "Tech": "Tech",
    "EXECUTIVE": "EXECUTIVE",
    "Executive": "Executive",
    "HARVARD": "HARVARD",
    "Harvard": "Harvard",
    "STANFORD": "STANFORD",
    "Stanford": "Stanford",
    "TECH ATS": "TECH ATS",
    "Tech ATS": "Tech ATS",
    
    "Klasik, %100 ATS uyumlu profesyonel stil.": "Classic, 100% ATS compliant professional style.",
    "Dinamik iki kolonlu çağdaş yapı.": "Dynamic two-column contemporary structure.",
    "Sade ve elit, modern ATS uyumlu tasarım.": "Simple and elite, modern ATS compliant design.",
    "Asimetrik ve görsel ağırlıklı premium stil.": "Asymmetrical and visual-heavy premium style.",
    "Koyu tema, badge beceriler, mono detaylar.": "Dark theme, badge skills, mono details.",
    "Kurumsal, temiz ve güvenli seçim.": "Corporate, clean, and safe choice.",
    "IT uzmanlarına özel ATS dostu düzen.": "ATS friendly layout specific to IT professionals.",
    "Wall Street editorial yaklaşımı.": "Wall Street editorial approach.",
    "Yalın, sade ve içerik odaklı.": "Lean, simple, and content-oriented.",

    "Kişisel": "Personal",
    "Özet": "Summary",
    "Deneyim": "Experience",
    "Eğitim": "Education",
    "Beceriler": "Skills",
    "Projeler": "Projects",
    "Y. Dil": "Languages",
    "Sertifikalar": "Certificates",
    "Gönüllü": "Volunteering",
    "Referanslar": "References",
    "Ek Ayarlar": "Extra Settings",
    "Fotoğraf": "Photo",
    
    "Ad Soyad": "Full Name",
    "Meslek / Unvan": "Job / Title",
    "E-posta": "Email",
    "Telefon": "Phone",
    "Konum (Örn: İstanbul, Türkiye)": "Location (e.g. London, UK)",
    "LinkedIn URL": "LinkedIn URL",
    "GitHub veya Portfolyo URL": "GitHub or Portfolio URL",
    "Profesyonel Özet": "Professional Summary",
    
    "Yeni Deneyim Ekle": "Add Experience",
    "Yeni Eğitim Ekle": "Add Education",
    "Yeni Beceri Ekle": "Add Skill",
    "Yeni Proje Ekle": "Add Project",
    "Yeni Dil Ekle": "Add Language",
    "Yeni Sertifika Ekle": "Add Certificate",
    "Yeni Gönüllü İşi Ekle": "Add Volunteering",
    "Yeni Referans Ekle": "Add Reference",
    
    "Şirket/Kurum Adı": "Company/Institution Name",
    "Pozisyon": "Position",
    "Tarih": "Date",
    "Devam Ediyor": "Present",
    "Açıklama (Opsiyonel)": "Description (Optional)",
    "Okul Adı": "School Name",
    "Bölüm": "Department",
    "Not Ortalaması (Opsiyonel)": "GPA (Optional)",
    "Beceri Adı": "Skill Name",
    "Beceri Seviyesi (Opsiyonel)": "Skill Level (Optional)",
    "Proje Adı": "Project Name",
    "Kullanılan Teknolojiler": "Technologies Used",
    "Proje Linki (Opsiyonel)": "Project Link (Optional)",
    "Dil Seçin...": "Select Language...",
    "Seviye": "Level",
    "Sertifika / Kurs Adı": "Certificate / Course Name",
    "Veren Kurum": "Issuing Organization",
    "Kurum Adı": "Institution Name",
    "Rol": "Role",
    "Referans Adı": "Reference Name",
    "Unvan / Şirket": "Title / Company",
    "İletişim Bilgisi": "Contact Info",
    "Renk Teması": "Color Theme",
    "CV Dili": "CV Language",
    "Boyut": "Size",
    
    "Tasarımı İndir (PDF)": "Download Design (PDF)",
    "Sadece Önizleme": "Preview Only",
    "Yeni CV": "New CV",
    "CV Kaydedildi!": "CV Saved!",
    "CV Yükleniyor...": "Loading CV...",
    "İndiriliyor...": "Downloading...",
    
    "Kayıtlı CV'lerim": "My Saved CVs",
    "Daha önce kaydettiğiniz özgeçmişleriniz burada listelenir.": "Your previously saved resumes are listed here.",
    "Henüz kaydedilmiş bir CV'niz bulunmuyor.": "You don't have any saved CVs yet.",
    "Hemen yeni bir CV oluşturarak başlayabilirsiniz.": "You can start right away by creating a new CV.",
    "Önizle": "Preview",
    "Giriş Başarılı!": "Login Successful!",
    "Hata": "Error",
    "Başarılı": "Success",
    "Siliniyor...": "Deleting...",
    "Silindi!": "Deleted!",
    "Lütfen giriş yapın.": "Please log in.",
    "Bağlantı kopyalandı!": "Link copied!",
    "Eksik alanlar var.": "There are missing fields.",
    
    "Örn: Yazılımcı CV - Mayıs 2026": "e.g. Developer CV - May 2026",
    "Örn: John Doe": "e.g. John Doe",
    "Örn: Yazılım Mühendisi": "e.g. Software Engineer",
    "Örn: İstanbul, Türkiye": "e.g. London, UK",
    "Kariyer hedeflerinizi ve öne çıkan niteliklerinizi kısaca anlatın...": "Briefly describe your career goals and key qualifications...",
    "Örn: Google": "e.g. Google",
    "Örn: Kıdemli Yazılım Geliştirici": "e.g. Senior Software Developer",
    "Örn: Ocak 2022 - Günümüz": "e.g. Jan 2022 - Present",
    "Neler başardınız? Hangi teknolojileri kullandınız?": "What did you achieve? Which technologies did you use?",
    "Örn: Stanford Üniversitesi": "e.g. Stanford University",
    "Örn: Bilgisayar Mühendisliği": "e.g. Computer Science",
    "Örn: 2018 - 2022": "e.g. 2018 - 2022",
    "Örn: 3.8 / 4.0": "e.g. 3.8 / 4.0",
    "Örn: ofis programları - excel - pptx": "e.g. office programs - excel - pptx",
    "Örn: E-Ticaret Sistemi": "e.g. E-Commerce System",
    "Örn: React, Node.js, MongoDB": "e.g. React, Node.js, MongoDB",
    "Örn: https://github.com/proje": "e.g. https://github.com/project",
    "Proje detayları...": "Project details...",
    "Örn: AWS Certified Developer": "e.g. AWS Certified Developer",
    "Örn: Amazon": "e.g. Amazon",
    "Örn: 2023": "e.g. 2023",
    "Örn: Kızılay": "e.g. Red Crescent",
    "Örn: Gönüllü Eğitmen": "e.g. Volunteer Instructor",
    "Gönüllü işinizin detayları...": "Details of your volunteer work...",
    "Örn: Jane Doe": "e.g. Jane Doe",
    "Örn: Yazılım Müdürü - Google": "e.g. Software Manager - Google",
    "Örn: jane@example.com - 555 123 4567": "e.g. jane@example.com - 555 123 4567",
    
    "CV Şablonları - Online CV Oluşturucu": "CV Templates - Online CV Builder",
    "Profesyonel CV şablonlarımızdan size en uygun olanı seçin.": "Choose the most suitable one from our professional CV templates.",
    "Premium SaaS deneyimi için 6 farklı tasarım arasından seçim yapın. Ortadaki odak kartı seçerek editör ekranına anında geçin.": "Choose from 6 different designs for a Premium SaaS experience. Select the center focus card to instantly switch to the editor screen.",
    "Tümü": "All",
    "Tüm Şablonlar": "All Templates",
    "Öğrenci": "Student",
    "Yazılım": "Software",
    "İş Dünyası": "Business",
    "Minimalist": "Minimalist",
    "Yaratıcı": "Creative",
    "ATS Dostu": "ATS Friendly",
    "Fotoğraflı": "With Photo",
    "Fotoğrafsız": "Without Photo",
    "Tek Sütun": "Single Column",
    "Çift Sütun": "Two Columns",
    "Ücretsiz": "Free",
    "ATS Uyumlu": "ATS Compliant",
    "Şablonu Kullan": "Use Template",
    "Bu Şablonla\\r\\n                                    Başla": "Start with this Template",
    "Bu Şablona Geç": "Switch to this Template",
    "Önizleme": "Preview",
    "Kurumsal ve zamansız iş başvuruları için güvenli seçim.": "Safe choice for corporate and timeless job applications.",
    "Dinamik iki kolon düzeni ile teknoloji ve yaratıcı roller için ideal.": "Ideal for tech and creative roles with its dynamic two-column layout.",
    "Yalın tipografi ve içerik odağı isteyen profesyoneller için.": "For professionals who want lean typography and content focus.",
    "Asimetrik kompozisyon, büyük fotoğraf alanları ve cesur vurgu çizgileri.": "Asymmetrical composition, large photo areas and bold emphasis lines.",
    "TECH MODE": "TECH MODE",
    "Dark mode hissi, badge beceriler ve teknik URL odaklı mono stil.": "Dark mode feel, badge skills and technical URL-oriented mono style.",
    "Yüksek yoğunluklu iki kolon ve serif tipografi ile üst düzey profil sunumu.": "High-density two-column and serif typography for high-level profile presentation.",
    "Dünya standardı, %100 ATS uyumlu, fotoğrafsız ve klasik serif profesyonel stil.": "World standard, 100% ATS compliant, photo-free and classic serif professional style.",
    "Modern, temiz, fotoğrafsız, geniş boşluklu, elit ATS uyumlu şablon.": "Modern, clean, photo-free, spacious, elite ATS compliant template.",
    "Yazılımcılar ve IT uzmanları için vurgulu renkler ve ATS uyumlu tek kolon düzen.": "Accent colors and ATS compliant single column layout for developers and IT professionals.",
    "Şablon ara...": "Search templates...",

    "Kendi CV'ni Oluştur": "Create Your Own CV",
    "Profesyonel CV'nizi dakikalar içinde oluşturun ✨": "Create your professional CV in minutes ✨",
    "Yazdır": "Print",
    "📄 PDF / Yazdır": "📄 PDF / Print",
    "Kullanım Koşulları - Online CV Oluşturucu": "Terms of Use - Online CV Builder",
    "Online CV Oluşturucu (\\\"Site\\\" veya \\\"Platform\\\") web sitesini ziyaret ederek veya kullanarak aşağıdaki kullanım koşullarını kabul etmiş olursunuz. Lütfen bu koşulları dikkatlice okuyunuz.": "By visiting or using the Online CV Builder (\\\"Site\\\" or \\\"Platform\\\") website, you agree to the following terms of use. Please read these terms carefully.",
    "1. Hizmetin Sağlanması": "1. Provision of Service",
    "Online CV Oluşturucu, kullanıcılarına profesyonel özgeçmiş hazırlama, kaydetme ve PDF formatında indirme hizmetlerini ücretsiz olarak sunar. Hizmetler \\\"olduğu gibi\\\" sunulmakta olup, kesintisiz veya hatasız olacağı garanti edilmemektedir.": "Online CV Builder offers professional resume preparation, saving, and PDF download services to its users free of charge. The services are provided \\\"as is\\\" and are not guaranteed to be uninterrupted or error-free.",
    "2. Kullanıcı Yükümlülükleri": "2. User Obligations",
    "Platformu kullanırken aşağıdaki kurallara uymayı kabul edersiniz:": "You agree to abide by the following rules when using the platform:",
    "Oluşturduğunuz özgeçmişlerde verdiğiniz bilgilerin doğruluğundan tamamen siz sorumlusunuz.": "You are fully responsible for the accuracy of the information you provide in the resumes you create.",
    "Site altyapısına zarar verecek, sistemleri kilitleyecek veya diğer kullanıcıların deneyimini olumsuz etkileyecek yazılımsal saldırı, spam veya zararlı işlemler yapmamayı taahhüt edersiniz.": "You undertake not to carry out software attacks, spam, or harmful operations that would damage the site infrastructure, lock systems, or negatively affect the experience of other users.",
    "Giriş bilgilerinizin güvenliğini sağlamak sizin sorumluluğunuzdadır.": "It is your responsibility to ensure the security of your login information.",
    "3. Fikri Mülkiyet": "3. Intellectual Property",
    "Platformumuzda bulunan CV şablon tasarımları, arayüz, logolar ve yazılımlar Online CV Oluşturucu'ya aittir. Oluşturduğunuz içeriklerin (özgeçmiş bilgileri) mülkiyeti ise size aittir.": "The CV template designs, interface, logos, and software on our platform belong to Online CV Builder. The ownership of the content you create (resume information) belongs to you.",
    "4. Hizmetin Değiştirilmesi veya Durdurulması": "4. Modification or Discontinuation of Service",
    "Platform, önceden haber vermeksizin hizmetleri kısmen veya tamamen durdurma, özelliklerini değiştirme veya sınırlama hakkını saklı tutar.": "The platform reserves the right to partially or completely suspend services, change their features, or limit them without prior notice.",
    "5. Sorumluluk Reddi": "5. Disclaimer of Liability",
    "Kullanıcıların özgeçmişlerinde yer alan bilgilerin doğruluğu ve bu CV'ler ile yapılan iş başvurularının sonuçları hakkında hiçbir sorumluluk kabul etmiyoruz.": "We accept no responsibility for the accuracy of the information in the users' resumes and the results of job applications made with these CVs.",
    "Gizlilik\\r\\n                    Politikası": "Privacy Policy",
    "Kullanım\\r\\n                    Koşulları": "Terms of Use",
    "Gizlilik Politikası": "Privacy Policy",
    "Kullanım Koşulları": "Terms of Use",
    "Gizlilik Politikası - Online CV Oluşturucu": "Privacy Policy - Online CV Builder",
    "Son Güncelleme:": "Last Update:",
    "7 Temmuz 2026": "July 7, 2026",
    "Online CV Oluşturucu olarak, gizliliğinize büyük önem veriyoruz. Bu gizlilik politikası, web sitemizi kullanırken topladığımız bilgileri, bu bilgileri nasıl kullandığımızı ve koruduğumuzu açıklamaktadır.": "As Online CV Builder, we attach great importance to your privacy. This privacy policy explains what information we collect when you use our website, how we use this information, and how we protect it.",
    "1. Toplanan Bilgiler": "1. Collected Information",
    "Hizmetimizi kullanırken aşağıdaki bilgileri toplayabiliriz:": "We may collect the following information when you use our service:",
    "Kayıt Bilgileri:": "Registration Information:",
    "E-posta adresiniz ve şifreniz (güvenli bir şekilde şifrelenmiş olarak).": "Your email address and password (securely encrypted).",
    "Özgeçmiş Verileri:": "Resume Data:",
    "Uygulamamız üzerinden oluşturduğunuz CV'lere girdiğiniz ad, soyad, iletişim bilgileri, eğitim ve iş deneyimi gibi profesyonel bilgiler.": "Professional information such as name, surname, contact information, education, and work experience that you enter into the CVs you create through our application.",
    "Çerezler (Cookies):": "Cookies:",
    "Oturum yönetimi ve site performansını analiz etmek amacıyla teknik çerezler kullanılmaktadır.": "Technical cookies are used for session management and analyzing site performance.",
    "2. Bilgilerin Kullanımı": "2. Use of Information",
    "Topladığımız bilgileri şu amaçlarla kullanırız:": "We use the information we collect for the following purposes:",
    "CV'lerinizi oluşturmak, düzenlemek ve bulut üzerinde güvenle saklamak.": "To create, edit, and safely store your CVs on the cloud.",
    "Farklı cihazlardan giriş yaptığınızda CV'lerinize erişiminizi sağlamak.": "To ensure access to your CVs when you log in from different devices.",
    "Sistem hatalarını tespit etmek ve kullanıcı deneyimini iyileştirmek.": "To detect system errors and improve user experience.",
    "3. Bilgilerin Korunması ve Saklanması": "3. Protection and Storage of Information",
    "Tüm kullanıcı verileri ve CV bilgileri Google Firebase'in güvenli sunucularında uçtan uca şifreli olarak (SSL/TLS) iletilir ve saklanır. Şifreniz bizim tarafımızdan dahi görülemez; Google'ın güvenli kimlik doğrulama altyapısı tarafından yönetilir.": "All user data and CV information is transmitted and stored end-to-end encrypted (SSL/TLS) on Google Firebase's secure servers. Your password cannot be seen even by us; it is managed by Google's secure authentication infrastructure.",
    "4. Veri Paylaşımı": "4. Data Sharing",
    "Kişisel bilgilerinizi ve özgeçmiş verilerinizi": "Your personal information and resume data are",
    "kesinlikle": "absolutely",
    "üçüncü şahıslara veya kurumlara satmıyoruz veya kiralıyoruz. Bilgileriniz sadece size hizmet sunmak amacıyla platformumuz içinde işlenir.": "not sold or rented to third parties or institutions. Your information is processed within our platform solely to provide service to you.",
    "5. Haklarınız (KVKK & GDPR)": "5. Your Rights (KVKK & GDPR)",
    "Kullanıcı olarak şu haklara sahipsiniz:": "As a user, you have the following rights:",
    "CV'lerinizi dilediğiniz zaman silebilirsiniz (sildiğinizde veritabanımızdan kalıcı olarak yok edilir).": "You can delete your CVs anytime (when deleted, they are permanently removed from our database).",
    "Hesabınızı ve hesabınıza bağlı tüm verileri tamamen silme talebinde bulunabilirsiniz.": "You can request the complete deletion of your account and all data linked to your account.",
    "Hangi verilerinizin işlendiğini öğrenme hakkına sahipsiniz.": "You have the right to know what data of yours is being processed.",
    "6. İletişim": "6. Contact",
    "Gizlilik politikamız veya verilerinizle ilgili her türlü soru ve talebiniz için destek ekibimizle iletişime geçebilirsiniz.": "For any questions or requests regarding our privacy policy or your data, you can contact our support team.",
    "Ana Sayfaya Dön": "Return to Home Page",
    
    "ATS Uyum Skoru": "ATS Compliance Score",
    "Geliştirilmeli": "Needs Improvement",
    "İyi": "Good",
    "Mükemmel": "Excellent",
    "ATS sistemleri için iletişim, özet, beceri ve\\r\\n                                deneyim sinyalleri analiz edilir.": "Contact, summary, skill, and experience signals are analyzed for ATS systems.",
    "Öneriler": "Suggestions",
    "Adınız Soyadınız": "Full Name",
    "Mesleğiniz / Unvanınız": "Job Title",
    "Örn: Ayşe Kaya": "e.g. Ayşe Kaya",
    "Örn: Frontend Geliştirici": "e.g. Frontend Developer",
    "ornek@mail.com": "example@mail.com",
    "+90 555 000 00 00": "+90 555 000 00 00",
    "İstanbul, 01.01.1990": "London, 01.01.1990",
    "İstanbul, Türkiye": "London, UK",
    "B Sınıfı": "Class B",
    "linkedin.com/in/...": "linkedin.com/in/...",
    "github.com/kullaniciadi": "github.com/username",
    "behance.net/kullaniciadi": "behance.net/username",
    "https://portfolyom.com": "https://portfolio.com",
    "https://... (resim URL'si)": "https://... (image URL)",
    "Kendinizi kısaca tanıtın. Deneyimlerinizi, güçlü yönlerinizi ve kariyer hedeflerinizi özetleyin...": "Briefly introduce yourself. Summarize your experience, strengths, and career goals...",
    
    "💾 CV'yi Kaydet": "💾 Save CV",
    "CV'nize bir isim verin. Aynı isimde kayıt varsa üzerine yazılacak.": "Give your CV a name. If a record with the same name exists, it will be overwritten.",
    "CV Adı": "CV Name",
    "⚠️ Maksimum 5 CV\\r\\n                kaydedebilirsiniz. Eski bir CV'yi silmeniz gerekiyor.": "⚠️ You can save a maximum of 5 CVs. You need to delete an old CV.",
    "CV Adı...": "CV Name...",
    "Kapat": "Close",
    "CV Oluşturucu": "CV Builder",
    "Online CV Oluşturucu - Ücretsiz ve Profesyonel Özgeçmiş Tasarımı": "Online CV Builder - Free and Professional Resume Design",
    "CV Önizleme - CV Oluşturucu": "CV Preview - CV Builder",
    "CV Görüntüle - Online CV Oluşturucu": "View CV - Online CV Builder",
    "⏳ CV Yükleniyor...": "⏳ Loading CV...",
    "Lütfen bekleyiniz.": "Please wait.",
    "👑\\r\\n                        Premium'a Geç": "👑\\r\\n                        Go Premium"
}'''

with open('c:/Users/Asus/Desktop/PROJECTS/Cv_olusturucu/js/i18n.js', 'r', encoding='utf-8') as f:
    content = f.read()

start_idx = content.find('const translations = {')
end_idx = content.find('};', start_idx) + 2

new_content = content[:start_idx] + 'const translations = ' + dict_str + ';' + content[end_idx:]

with open('c:/Users/Asus/Desktop/PROJECTS/Cv_olusturucu/js/i18n.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('Dictionary updated in i18n.js')
